### ISSUE TITLE
Clean up discussion of APIs

### ISSUE THREAD

**Issue by peterverhaar** [cdsleiden/python-tutorial#18]
We can improve our explanation of APIs in several ways (I think):

* not all APIs are Web APIs
* use a more accessible API than Wikipedia (weird lists of lists) or ORCID
* improve explanation of ex 10.4 ("capture" is not really what happens) and the solution that adds a web map without context
* remove unused imports from ex 10.4, add more scaffolding
* mark URL encoding as advanced, because Requests takes care of this for us

**Comment by bencomp** [comment]
Copied from https://github.com/peterverhaar/python_tutorial/issues/9
