### ISSUE TITLE
Returning the function as a value

### ISSUE THREAD

**Issue by peterverhaar** [cdsleiden/python-tutorial#61]
The section in the tutorial on the use of a function without parentheses and "getting the function as a value" is quite unclear. Why is this relevant? I would suggest removing this section and simply stress that functions always need to be used with parentheses

**Comment by bencomp** [comment]
Indeed not using parentheses is an advanced use of functions. However, in class we sometimes see that learners forget to use them when they should and my idea was to show what happens then. I tried to clarify in #101 that you almost always need parentheses, but also that `help` takes a function without parentheses.
