### ISSUE TITLE
Check OSM attribution in map solution

### ISSUE THREAD

**Issue by bencomp** [cdsleiden/python-tutorial#87]
The example solution to the OpenStreetMap exercise that builds an HTML file with map includes attribution to OpenStreetMap contributors with CC-BY-SA 2.0 license, but I think that is incorrect. (I vaguely remember the data relicense hassles as an OSM contributor...)

**Comment by bencomp** [comment]
The data is licensed under the [ODbL](https://opendatacommons.org/licenses/odbl/), the documentation under CC-BY-SA.

**Comment by peterverhaar** [comment]
The code for OpenStreetMap was removed. We are working on a separate set of notebooks on digital mapping
